### ISSUE TITLE
Choose only several effects 

### ISSUE THREAD

**Issue by raphaelgoetter** [elrumordelaluz/csshake#20]
Hello,

Thank you for your great work !

I find a bit annoying to have to download all the effects at once, would it be possible to download only the shake effect(s) chosen in the CSS file ? (something like a checkbox)

Thank you

**Comment by elrumordelaluz** [comment]
@raphaelgoetter since in the [last release](https://github.com/elrumordelaluz/csshake/releases/tag/v1.5) I reduce the code into only one mixin to generate the animations, now is easier to generate separated classes. Also added a [Download center](http://csshake.surge.sh/) with the core animations to download separately. Thanks again!
