### ISSUE TITLE
Elements changing width

### ISSUE THREAD

**Issue by punshonjm** [elrumordelaluz/csshake#42]
This issue is likely caused because I'm using Bootstrap but when the shake class is applied to some elements, it causes the elements below to become inline, even if set to blocks

Issue recreated here: https://codepen.io/anon/pen/QMOOxJ

This is because on the display: inline-block, I've commented it out in the local copy and it appears to prevent the issue from happening but wanted to check what the particular reason behind changing the element to an inline-block was, in case it causes effects elsewhere when using your plugin.

**Comment by elrumordelaluz** [comment]
@punshonjm thanks for reporting the issue.
At the beginning the _shaked_ element needs a `display` property to allow transformations. 
You are absolutely right that removing/commenting this property prevents this strange behaviour. 
A simple fix (PR welcome!) could be to switch `display: inline-block` that assume a specific relation with the layout/context into `display: inherits` or test again use cases without `display` property at all. 
In case you want to contribute with a PR (could be awesome!), should be necessary to test with different kind of html elements because browsers assign a default `display` prop in some elems.
In case I found a document with this assumptions will share here.

Otherwise, when as soon as I have a peace of time I'll fix this.

Thanks again,
